import z from 'zod'

export const EntitySchema = z.object({
  ID: z.number().int().positive().optional(),
  TIPO_ENTIDAD: z.string().optional(),
  TIPO_DOC_IDENT: z.number().int().positive().optional(),
  DOCUMENTO_IDENT: z.string().optional(),
  NOMBRES: z.string().optional(),
  APELLIDOS: z.string().optional(),
  SEXO: z.string().optional(),
  ESTADO_CIVIL: z.string().optional(),
  TELEFONO: z.string().optional(),
  TIPO_EMPELO: z.string().optional(),
  NOMBRE_EMPRESA_TRABAJO: z.string().optional(),
  OCUPACION: z.string().optional(),
  POSICION_EMPRESA: z.string().optional(),
  MONEDA_INGRESO: z.string().optional(),
  INGRESO_PROMEDIO: z.number().optional(),
  OTRO_INGRESO: z.number().optional(),
  RAZON_OTRO_INGRESO: z.string().optional(),
  EMAIL: z.string().email('Formato de email inválido').optional(),
  ID_PAIS: z.string().optional(),
  ID_PROVINCIA: z.number().int().positive().optional(),
  ID_MUNICIPIO: z.number().int().positive().optional(),
  ID_CIUDAD: z.number().int().positive().optional(),
  DESC_DIRECCION: z.string().optional(),
  FECHA_NACIMIENTO: z.coerce.date().optional(),
  ESTADO: z.string().min(1, 'El estado es requerido'),
})
